# 注册 / 卸载 Windows 计划任务：每天定时跑邮件日报
# 用法（不需要管理员；但如果在 DSH 沙箱里跑，写任务存储会被拦，需要放宽权限）：
#   .\install-task.ps1                 # 默认每天 20:00
#   .\install-task.ps1 -Time 07:30
#   .\install-task.ps1 -Visible        # 不用隐藏窗口的 VBS 包装（调试用，会闪一下黑窗）
#   .\install-task.ps1 -Uninstall
#   .\install-task.ps1 -Time 20:00 -WakeToRun   # 睡眠时也到点唤醒（见 README「定时与开机的关系」）
[CmdletBinding()]
param(
  [string]$TaskName = "MailDigest-Daily",
  [string]$Time = "20:00",
  [switch]$Visible,
  [switch]$WakeToRun,
  [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot

function Run-SchTasks([string]$Arguments) {
  $out = & cmd.exe /c "schtasks $Arguments" 2>&1
  return @{ Code = $LASTEXITCODE; Output = ($out | Out-String).Trim() }
}

if ($Uninstall) {
  $r = Run-SchTasks "/Delete /TN `"$TaskName`" /F"
  if ($r.Code -eq 0) { Write-Host "[OK] 已删除计划任务 $TaskName" -ForegroundColor Green }
  else { Write-Host "[--] 删除失败或任务不存在：$($r.Output)" -ForegroundColor Yellow }
  return
}

# ---------- 1) 确定 node.exe（优先项目自带 runtime\node.exe，避免依赖 DSH）----------
$node = Join-Path $root "runtime\node.exe"
if (-not (Test-Path $node)) {
  $found = Get-Command node.exe -ErrorAction SilentlyContinue
  if ($found) { $node = $found.Source }
}
if (-not (Test-Path $node)) {
  throw "找不到 node.exe，请把 node.exe 放到 $root\runtime\"
}
if (-not (Test-Path (Join-Path $root "main-outlook.mjs"))) { throw "找不到 $root\main-outlook.mjs" }

New-Item -ItemType Directory -Force -Path (Join-Path $root "logs") | Out-Null

# ---------- 2) 构造要执行的命令（默认用 VBS 包装，避免弹黑窗）----------
# 注意：入口是 main-outlook.mjs（Outlook COM 通道）。main.mjs 是旧的 Graph 通道，
# 需要学校管理员同意才能用，保留作备用，不要挂到计划任务上。
$logFile = Join-Path $root "logs\task.log"
$inner = "cd /d `"$root`" && `"$node`" main-outlook.mjs >> `"$logFile`" 2>&1"

if ($Visible) {
  $exec = "cmd.exe"
  $execArgs = "/c $inner"
} else {
  $vbs = Join-Path $root "run-hidden.vbs"
  # VBScript 字符串里的双引号必须写成两个双引号，否则会语法错误
  $innerVbs = $inner -replace '"', '""'
  $vbsBody = @"
' Generated by install-task.ps1 - run daily mail digest with a hidden window
' bWaitOnReturn=True + WScript.Quit(rc): pass node's exit code back to Task Scheduler
' so "Last Run Result" is meaningful (0 ok / 2 needs re-login / 3 other failure).
Set sh = CreateObject("WScript.Shell")
rc = sh.Run("cmd /c $innerVbs", 0, True)
WScript.Quit rc
"@
  # VBS 用 ASCII 写，避免编码问题（内容本身没有中文）
  [System.IO.File]::WriteAllText($vbs, $vbsBody, [System.Text.Encoding]::ASCII)
  $exec = "wscript.exe"
  $execArgs = "`"$vbs`""
}

# ---------- 3) 生成任务 XML 并注册 ----------
$userId = "$env:USERDOMAIN\$env:USERNAME"
$startBoundary = (Get-Date -Format "yyyy-MM-dd") + "T" + $Time + ":00"
$xmlPath = Join-Path $env:TEMP "MailDigest-Daily.xml"

$xml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>每天生成 Outlook 邮件日报并发回自己邮箱（mail-digest）</Description>
    <URI>\$TaskName</URI>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>$startBoundary</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay>
        <DaysInterval>1</DaysInterval>
      </ScheduleByDay>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>$userId</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>$($WakeToRun.IsPresent.ToString().ToLower())</WakeToRun>
    <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>
    <RestartOnFailure>
      <Interval>PT10M</Interval>
      <Count>2</Count>
    </RestartOnFailure>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>$exec</Command>
      <Arguments>$execArgs</Arguments>
    </Exec>
  </Actions>
</Task>
"@
# schtasks 读 XML 时按声明解析，用 UTF-16 写最稳
[System.IO.File]::WriteAllText($xmlPath, $xml, (New-Object System.Text.UnicodeEncoding($false, $true)))

$reg = Run-SchTasks "/Create /XML `"$xmlPath`" /TN `"$TaskName`" /F"
$method = "XML"
if ($reg.Code -ne 0) {
  Write-Host "[!] XML 方式注册失败，回退到命令行方式：$($reg.Output)" -ForegroundColor Yellow
  $tr = "$exec $execArgs"
  $reg = Run-SchTasks "/Create /TN `"$TaskName`" /TR `"$tr`" /SC DAILY /ST $Time /F"
  $method = "命令行"
}
if ($reg.Code -ne 0) {
  Write-Host "[X] 注册失败：$($reg.Output)" -ForegroundColor Red
  exit 1
}

# ---------- 4) 回读确认 ----------
$q = Run-SchTasks "/Query /TN `"$TaskName`" /FO LIST /V"
Write-Host "[OK] 已注册计划任务（$method 方式）" -ForegroundColor Green
foreach ($k in "TaskName", "Next Run Time", "Status", "Task To Run", "Start In", "Logon Mode", "Schedule Type", "Start Time", "Run As User") {
  $line = ($q.Output -split "`r?`n" | Where-Object { $_ -match "^\s*$([regex]::Escape($k))\s*:" })
  if ($line) { Write-Host ("     " + $line.Trim()) }
}
Write-Host "     日志：$logFile"
Write-Host ""
Write-Host "手动试跑一次： schtasks /Run /TN `"$TaskName`""
Write-Host "查看结果：     Get-Content `"$logFile`" -Tail 40 -Encoding UTF8"
